README.md

Add link to our meeting minutes

---

README.md

add links to our draft docs

---

presentations/README.md

Provides links to uploaded and external presentations.

Create readme with links

---

README.md

Add info about upcoming f2f

---

proposals/README.md

As discussed on the wg meeting, sending a draft for the README.

Adding README to proposals folder

---

README.md

Just tweak some spacing before my next round of real edits

---

README.md
proposals/README.md

Update README for CloudEvents and for proposals process

---

README.md
whitepaper/README.md

Also we should version the whitepaper.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

Clean up README

---

whitepaper/README.md

I'd like to update my information in the paper.
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

Update Author Alex Ellis

---

presentations/README.md

Also put presentations in chronological order.

Added Serverlessconf Paris lightning talk

---

whitepaper/README.md

Updated the next steps section to include "Provide guidance on serverless security topics", and added a reference to the Serverless Architectures Security Top 10 Guide in Appendix B

Updated the Next Steps & Appendix B

---

whitepaper/README.md

fix some typos

---

whitepaper/README.md

distinguish between md and pdf version of whitepaper

---

whitepaper/README.md

* Fix bold usage
* Update link to section

Fixed markdown formatting

---

proposals/README.md

add work stream proposals

---

proposals/README.md
proposals/function-logging.md

Signed-off-by: Yaron Haviv <yaronh@iguazio.com>

add iguazio workstream proposals

---

proposals/cloudevents/README.md

add a warning that the doc is old

---

whitepapers/serverless-overview/README.md

Goal here was to elaborate on the potential benefits of a workflow tool beyond orchestrating a set of functions to complete some outcome--specifically, I mention visibility, resolving issues that are blocking a workflow instance, and analytics / auditing. 
I also included a link to a blog post where someone built a POC with Fn Project and Zeebe (zeebe.io), a workflow engine. Full disclosure: I work on Zeebe, and that's why I'm aware of the blog post, but I did not have any influence over the decision to write it or how it was written (it comes from a "neutral" third party). Happy for any feedback over whether the link is appropriate and general input on the changes.

Additions to 'Serverless Function Workflow' section of whitepaper

---

workflow/spec/spec.md

* updated table of contents
* restructured doc to group things together little better
* fixed some wording
* updated anchor links
* updated json: changed all of the json examples to be actual json format. One change you might want to look at is that the name of states and triggers is no longer like:
```
"SOME-NAME": { ... } 
```
but a name field (which makes more sense for implementors):
```
{
"name": "SOME-NAME",
...
}
```

formatting and json updates

---

workflow/spec/contributors.md

Just a small contribution but now I will review the following PR:
https://github.com/cncf/wg-serverless/pull/89
For the spec notation

Adding to contributor section

---

workflow/spec/schema/serverless-workflow-schema-01.json
workflow/spec/spec.md

The document was missing filter definition which is described in the "Filter Mechanism" section. This adds it.

Adding filter definition

---

workflow/spec/spec.md

I didn't catch this issue during review, fixing nextState property for subflow state.

Fixing SubFlow state nextState property

---

workflow/spec/community/contributors.md
workflow/spec/community/open-source.md
workflow/spec/community/readme.md
workflow/spec/governance/owners.md
workflow/spec/governance/readme.md
workflow/spec/owners.md
workflow/spec/readme.md

This pr updates the community information and structures the community and governance info.

Updating project community information

---

workflow/spec/governance/owners.md
workflow/spec/governance/readme.md

* Adds Mauricio
* Updates Governance

Owners and Governance docs updates

---

workflow/spec/community/open-source.md

This adds the serverless workflow cli validation tool i created (open source so adding here for community to see and use): https://github.com/serverless-workflow/workflow-linter-cli

updating community open source document

---

workflow/spec/community/open-source.md

I also created a visual studio code extension that adds json schema support -- https://marketplace.visualstudio.com/items?itemName=tsurdilovic.workflow-schema-vscode
adding it to list of open source contributions

Adding Visual Studio Code extension to open source contributions

---

workflow/spec/schema/serverless-workflow-schema-01.json
workflow/spec/spec.md

currently we have to use function name to define its resource uri. this fixes the issue

fixing function definition

---

workflow/spec/schema/serverless-workflow-schema-01.json
workflow/spec/spec.md

This fixes issues like missing required field and types in the json schema definition for spec.

JSON Schema fixes

---

workflow/spec/spec.md

This just fixes spelling errors in spec document

Fixing spelling errors

---

workflow/spec/governance/owners.md
workflow/spec/governance/readme.md

Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
I am removing myself from owners. I will continue adding comments or participating when possible if it is fine for you but I can't consider myself an owner any more.

Remove ruben from owners

---

workflow/spec/governance/readme.md

related to https://github.com/cncf/wg-serverless/issues/116

Governance update

---

workflow/spec/spec.md

This change is to make the abstract section of the spec much clearer than before.

updating abstract

---

workflow/spec/spec.md

just small update to the specification details section. the current one has some broken sentences.
also using this pr for small fixes:
- removing unneeded pattern
- adding link for extensions element in parameter table
- fixing issues with parameter names and description

specification details update + small fixes

---

workflow/spec/schema/serverless-workflow-schema-01.json
workflow/spec/spec.md

just small update - adding proper links to json schema, json/json object, jsonpath
for readers.

Adding links to json schema / json/json object, jsonpath

---

workflow/spec/spec-examples.md
workflow/spec/spec.md

Small fixes

---

workflow/infra/workflow-crd.yaml

This PR reflects what is described in this issue: https://github.com/cncf/wg-serverless/issues/130
This provides an initial version of a Kubernetes CRD to be used as an API for different cloud providers to integrate with Workflows.

[workflow] Workflow Infrastructure Kubernetes CRD Integration 

---

workflow/spec/schema/serverless-workflow-schema-01.json

Fixes schema syntax error and reformats it

Fixing workflow schema

---

workflow/spec/readme.md

Goals described here: 
https://github.com/cncf/wg-serverless/issues/130

Updating description with larger, but well-scoped goals

---

workflow/spec/schema/serverless-workflow-schema-01.json
workflow/spec/spec-examples.md
workflow/spec/spec-extending.md
workflow/spec/spec.md

* changes "functionref" to "functionRef"
* changes "refname" to "refName"

"functionRef" and "refName"

---

workflow/spec/readme.md
workflow/spec/references.md
workflow/spec/spec-examples.md
workflow/spec/spec-extending.md
workflow/spec/spec-usecases.md
workflow/spec/spec.md

Just a bunch of small formatting changes.

Document formatting updates

---

workflow/spec/spec.md

Removing duplicated onError property

Removing duplicated onError property

---

workflow/spec/readme.md
workflow/spec/spec.md

* Updates the main description of the specification to make it more clear. Also aligns it with the introduction section of the main spec document.
* Adds meeting time information
* Adds meeting minutes information

Update main readme doc

---

workflow/spec/community/contributors.md

Adding Fako Menge to list of contributors

---

workflow/spec/spec.md

Formatting updates for spec doc

Formatting updates

---

workflow/spec/readme.md
workflow/spec/schema/serverless-workflow-schema-v01.json
workflow/spec/spec.md

Preparing for version 0.1

---

workflow/spec/roadmap.md

updating roadmap

---

workflow/spec/spec.md

* add callback state link
* move description to bottom of section as its done in others

Update function def description

---

workflow/spec/examples.md
workflow/spec/extending.md
workflow/spec/references.md
workflow/spec/spec.md
workflow/spec/usecases.md

Another round of spell checking docs

Spell check on spec documents

---

workflow/spec/schema/serverless-workflow-schema.json
workflow/spec/spec.md

Fixes and aligns property descriptions in schema and spec doc
Removes a not-needed required parameter
Spelling

Property description fixes in spec and schema

---

workflow/spec/references.md
workflow/spec/roadmap.md

Fixes issues @SwEngin found for issue https://github.com/cncf/wg-serverless/issues/198

Fixing links - Issue 198

---

workflow/spec/community/contributors.md

@SwEngin can you please take a look to make sure I got the info correct? Thanks.

Adding Mona Borham to list of community contributors

---

workflow/spec/examples-brigade.md
workflow/spec/roadmap.md

Adds examples doc comparing and contrasting the Brigade JavaScript markup and the YAML markup of the Serverless Workflow spec.

Adding Brigade examples doc

---

README.md

Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

Update SW links in Readme

---

whitepapers/serverless-overview/README.md

We should conform to the Inclusive Naming Initiative https://www.cncf.io/announcements/2020/11/18/global-technology-leaders-and-organizations-join-to-eradicate-racial-bias-from-code/

alternative to term "slave"

---

README.md

explain how we deal with sub-projects

---

whitepapers/serverless-overview/README.md

Thanks for this fantastic work. 
I was going through the paper and found it could use a couple of spell/grammar updates, hence the PR. 
Please let me know the feasibility. Thanks

Minor updates: Spelling and Grammar checks
