- whitepaper/README.md
* corrected the official name to Azure Functions (not Azure Cloud Functions)
* removed the locale from the Azure docs URLs - this allows the site to redirect to the appropriate locale
> changes related to Azure Functions

- whitepaper/README.md
PureSec recently modified the Serverless Security Top 10 guide, which is now a public Github project. I modified the relevant links/references.
> Modified the SAS Top 10 link to point to the Github project

- workflow/spec/spec.md
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
* Replace non-English characters
* Add alt text for diagrams
* Remove trailing `#` for headers
* There should be only one H1 (# Title)
* Wrap code and use spaces instead of tabs
* Remove extra spaces and line breaks
> Fix markdown and remove non-English characters

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
time based properties such as "timeout" and "retry-interval" are defined as "in seconds" which is not very user friendly. instead we should use the ISO 8601 dat and time format -- https://www.iso.org/iso-8601-date-and-time-format.html
which is international standard and much more intuitive to represent time and delays etc.
> Changing time values from seconds to ISO 8601 format

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec.md
There is no need for us to have an explicit end state. in this pr:
* Adding "starts-at" property to workflow and branch definitions. This property defines the name of the state which is the starting state of the workflow.
* Adding "end" property to each state which states if this state is the ending state of the workflow.
* Removes end state
* Updates text and small fixes
I think this is a much better option and will:
* make the overall json shorter
* allow more flexibility for implementations
* follows closer other workflow impls such as step functions for example
> Removing end state

- workflow/spec/spec.md
I made a small error during a rebase of previous PR merge -- this fixes it. Maybe we can get a quick "LGTM" for this as it fixes master formatting. Thanks.
> fixing markup error after a rebase

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec.md
This PR updates the workflow state transitions.
Currently state transitions are based on the "next-state" property which should match an existing state name. Issues with that are:
* State name should be primarily used for display purposes (in notation for example)
* State name can include "special" (i18n) characters which can cause issues for implementations.
* There could be multiple states with the same name if the users chose to
So overall "name" property of a state does not guarantee uniqueness and can lead to transition problems/ambiguity.
In addition, the current transition based on "next" or "next-state" is exactly the same as in aws step functions. Even if that is probably a good strategy there, step functions have closed system implementation where they can guarantee uniqueness …
> Updating state transitions

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
State Description (also included in spec.md with this change):
********
It is often the case that you want to group your workflows into small, **reusable** logical units that perform certain needed functionality.
Even tho you can use the Event state to call an externally deployed services (via function), at times
there is a need to include/nest another serverless workflow (from classpath/local file system etc). In that case you would use the SubFlow State.
It also allows users to model their workflows with reusability and logical grouping in mind.
This state allows you to include/nest a uniquely identified sub-workflow and start its execution. 
Another use of this state is within [branches](#parallel-state-branch) of the [Parallel State](#Parallel-State). Instead of having to define all …
> Proposal for new state: SubFlow State

- README.md
Happen to see the broken links.
Old link with `San Francisco` not work, I guess it's a bug of [timezone converter](http://www.thetimezoneconverter.com/).
> Fix broken timezone converter link

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
Switch state choices had some errors, this fixes them.
* Single state should not be an array type
* Not state should not be an array type
* Updated required params
* Fixed typos
* Simplified operator enum values (there is no reason to have the "string-based" comparators...that seems just to be a copy of ones that are in aws step functions...). Also the english spelling makes more sense to readers.
> Update to switch state choices

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
This updates the retry definition of actions. Main reason for update is that currently retry is a single element and it should be an array of retry definitions each matching on the return of the function call.
* Renamed to retry-when and is an array of retry definitions
* Retry definition parameters: match, interval, max-retry, next-state
* Added "default" parameter to Action definition. This defines the state to transition to if the function call fails (error) and none of the retry definitions define a match for it.
> Update retry in action definition

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
This pr adds looping behavior to each state.
Instead of having a single state which allows looping over some data collection, in our case it makes more sense to add looping to each state defined. 
Looping happens over each element of a input collection. In addition a completion condition can be set which if true stops looping. 
If a state defines data results, each iteration/loop adds the states results to the output collection.
After each iteration/loop users can define a time delay to wait before next iteration/loop can start.
> State Looping behavior

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec-extending.md
- workflow/spec/spec.md
This pr updates state transitions definition. 
Instead of just having "nextState", this adds a "transition" object with two properties:
"nextState" and "condition" (optional)
The first one works as before, however "condition" allows users to restrict/guard transitions by evaluating the states data output.
This is important so that we can prevent harmful transitions from happening.
Also this gives the ability to in future secure transitions etc.
An example is given in the spec description
This also fixes some existing examples json.
> update state transitions

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec-extending.md
- workflow/spec/spec.md
Functions are now defined similar to triggers and can be referenced within actions of event and operation states. 
Makes functions reusable between defined actions.
Functions are referenced via "functionref" property in actions. Function properties are defined inside functionref of actions.
Also this pr:
* changes "triggerDefs" to "triggers"
* renames retry definition "match" to "condition" so its a proper condition and not a string
> Reusable functions - referenced in actions

- workflow/spec/spec.md
Another set of general fixes (typos, formatting, rewording).
Only notable thing maybe is I moved the "use cases" section to the bottom of the document.
This is because currently use cases section needs an overhaul and is too complex to have right at the top of the page. Once revised we should move it back to the top.
**added** - fixed loop parameter in documentation to not be required, as per discussion in https://github.com/cncf/wg-serverless/issues/140
> Another set of general fixes

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec.md
As discussed we wanted to remove looping from being part of each individual state into its own state construct. 
This PR adds the "ForEach" state which is used to iterate over a JSON array in its data input. 
The documentation is spec.md has its schema definition, parameter description as well as an example. 
Also updated spec-examples.md updating the looping example to use ForEach state instead of "loop" parameter.
> New State - ForEach

- workflow/spec/spec-examples.md
- workflow/spec/spec.md
Describes YAML support for workflow definitions.
Updates all examples in spec.md and spec-examples.md to show 
both JSON and YAML workflow definitions side-by-side.
You can visually see what updates look like:
https://github.com/tsurdilo/wg-serverless/blob/yamlsupport/workflow/spec/spec.md
https://github.com/tsurdilo/wg-serverless/blob/yamlsupport/workflow/spec/spec-examples.md
> YAML support for workflow definitions

- workflow/spec/spec.md
Just small fix to remove loop parameter in operation state. It should not be there.
> Removing loop parameter in operation state

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
Removing execStatus property as:
* we do not describe currently what it does
* we do no explain how it is set during workflow execution
* we added workflow data input / output which can contain this information
I will revisit this soon and propose an alternative way for it then we can discuss, but for now this property is useless
> Removing execStatus property

- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec.md
**Why**: Currently both workflow as well as states have a data input and data output which are defined to be JSON. There is no way to express what format this data should adhere to. 
This is hard on users as they do not understand the expected data that may be needed to start a particular workflow instance, as well as what data to expect as result. Same for states data.
**What**: Adding to both workflow and each state two properties:
"dataInputSchema" and "dataOutputSchema". These properties allow users to link to a JSON Schema definition which describes the format for workflow/state expected data input/output.
Implementations can chose to strictly adhere to these schemas. 
This also allows tooling to use this information to document the expected data inputs/outputs.
> Workflow and state data input/output schema definition

- workflow/spec/community/open-source.md
- workflow/spec/schema/serverless-workflow-schema-01.json
- workflow/spec/spec-examples.md
- workflow/spec/spec.md
Clearly defines onError and retry definitions for states.
retry only allowed in Event, Operation, Parallel, and ForEach states. 
Added examples on how to use onError, retry, and combination of both for powerful error handling within states.
> onError and retry definition updates

- workflow/spec/roadmap.md
We really need a roadmap document so can show what has been done and what we are planning to do.
Please review and give comments if anything needs to be added to the "Setup" milestone.
You can see the parsed markdown here: https://github.com/tsurdilo/wg-serverless/blob/addroadmap2/workflow/spec/roadmap.md
> Adding spec roadmap document

- workflow/spec/governance/owners.md
Manuel is heavily involved with the specification and has shown alot of interest and dedicated his time on it. He has shown deep knowledge of the subject and is driving our meetings and work on the primer document.
> Adding Manuel Stein to list of spec owners

- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Adds new parameter to retry definition:
**multiplier** :  Multiplier value by which interval increases during each attempt (ISO 8601 time format). For example: "PT3S" meaning the second attempt interval is increased by 3 seconds, the third interval by 6 seconds and so on.
> Add multiplier param to retry definition

- workflow/spec/governance/owners.md
As suggested by @tsurdilo, @salaboy and I decided that it would be more suitable for the workflow project to switch roles.
> Replace Mauricio with Falko as owner representing Camunda

- workflow/spec/examples.md
- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Renames Relay state to Inject state so it's name makes more sense.
After getting some info from community, one of the bigger complaints was that noone understood what the name "Relay" means in relay state. It is a state that injects static data into the state data input. So from that changing:
Relay State / inject property 
to
Inject State / data property
to clearly describe that this is a state that "injects" "data".
> Rename Relay to Inject state

- workflow/spec/roadmap.md
- workflow/spec/spec.md
Updates the state definitions table:
* adds new column "Can be workflow start state"
* adds new column "Can be workflow end state"
This is to clearly show that switch state cannot be a workflow end state up-front in this table.
> Update state definitions table

- workflow/spec/examples.md
- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Updates Switch state:
* renames "choices" to "conditions"
* Removes the unnecessary "and "not" "or" choices and replaces them with condition definitions
* Adds more values as well as "Custom" value to condition operator
* Updates all examples
Reason: Our Switch state is very important state in spec however was way too complex to use. It acts as an exclusive gateway so the docs and its definition have been updated to clearly state its purpose. The different choices were not needed and just made things more complicated than should be, so they are removed.
> Updating Switch State

- workflow/spec/examples.md
- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Moves the waitForCompletion property from branch to parallel state.
The parallel state itself needs to determine how to "join" branches, and not each branch itself.
> Parallel State - waitForCompletion update

- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Actions execute functions, which can time out. Adding timeout property so this can be handled with states retry/onError definitions.
> Adding timeout property for actions

- workflow/spec/examples.md
- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
* Add "produceEvent" property to transitions
* Renames "nameRef" to "eventRef" to make it clear what it is
Reason: Event state consumes events, end definitions of states can produce events.
It is very useful to be able to also produce events during state transitions.
It eliminates the need of having a dedicated state just to produce a CE.
> Add ability to produce event during state transition

- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Currently in produceEvent, the data is just a string which is a json path expression selecting parts of the state data. In some cases you want to build your own data which may use the state data if needed for the produced event. 
This change allows users to do both.
> produceEvent data property update

- workflow/spec/examples-argo.md
- workflow/spec/examples.md
- workflow/spec/extending.md
- workflow/spec/roadmap.md
- workflow/spec/schema/serverless-workflow-schema.json
- workflow/spec/spec.md
Currently we enforce use of uppercase types and enums. This is not really the norm especially with our markup types (json/yaml). Changing to lowercase. Implementations can choose to ignore case or not.
> Change all uppercase properties and enum types to lowercase

- workflow/spec/roadmap.md
- workflow/spec/spec.md
Just adds section to describe how exceptions thrown in branches of parallel state can be handled. 
This should be merged before https://github.com/cncf/wg-serverless/pull/243 if possible :)
> Add Exception Handling section for Parallel State

- workflow/spec/spec.md
Google links directly to this doc for a "serverless workflow specification" search in its results. 
Adding the "We have moved" image here as well so readers know to go to the new repo where all the updates are now happening.
> Adding 'we have moved' to spec doc
